export const countries = [
  { key: 'af', value: 'Afghanistan' },
  { key: 'ax', value: 'Aland Islands' },
  { key: 'al', value: 'Albania' },
  { key: 'dz', value: 'Algeria' },
  { key: 'as', value: 'American Samoa' },
  { key: 'ad', value: 'Andorra' },
  { key: 'ao', value: 'Angola' },
  { key: 'ai', value: 'Anguilla' },
  { key: 'aq', value: 'Antarctica' },
  { key: 'ag', value: 'Antigua and Barbuda' },
  { key: 'ar', value: 'Argentina' },
  { key: 'am', value: 'Armenia' },
  { key: 'aw', value: 'Aruba' },
  { key: 'au', value: 'Australia' },
  { key: 'at', value: 'Austria' },
  { key: 'az', value: 'Azerbaijan' },
  { key: 'bs', value: 'Bahamas' },
  { key: 'bh', value: 'Bahrain' },
  { key: 'bd', value: 'Bangladesh' },
  { key: 'bb', value: 'Barbados' },
  { key: 'by', value: 'Belarus' },
  { key: 'be', value: 'Belgium' },
  { key: 'bz', value: 'Belize' },
  { key: 'bj', value: 'Benin' },
  { key: 'bm', value: 'Bermuda' },
  { key: 'bt', value: 'Bhutan' },
  { key: 'bo', value: 'Bolivia' },
  { key: 'bq', value: 'Bonaire, Sint Eustatius and Saba' },
  { key: 'ba', value: 'Bosnia and Herzegovina' },
  { key: 'bw', value: 'Botswana' },
  { key: 'bv', value: 'Bouvet Island' },
  { key: 'br', value: 'Brazil' },
  { key: 'io', value: 'British Indian Ocean Territory' },
  { key: 'bn', value: 'Brunei Darussalam' },
  { key: 'bg', value: 'Bulgaria' },
  { key: 'bf', value: 'Burkina Faso' },
  { key: 'bi', value: 'Burundi' },
  { key: 'kh', value: 'Cambodia' },
  { key: 'cm', value: 'Cameroon' },
  { key: 'ca', value: 'Canada' },
  { key: 'cv', value: 'Cape Verde' },
  { key: 'ky', value: 'Cayman Islands' },
  { key: 'cf', value: 'Central African Republic' },
  { key: 'td', value: 'Chad' },
  { key: 'cl', value: 'Chile' },
  { key: 'cn', value: 'China' },
  { key: 'cx', value: 'Christmas Island' },
  { key: 'cc', value: 'Cocos (Keeling) Islands' },
  { key: 'co', value: 'Colombia' },
  { key: 'km', value: 'Comoros' },
  { key: 'cg', value: 'Congo' },
  { key: 'cd', value: 'Congo, Democratic Republic of the Congo' },
  { key: 'ck', value: 'Cook Islands' },
  { key: 'cr', value: 'Costa Rica' },
  { key: 'ci', value: "Cote D'Ivoire" },
  { key: 'hr', value: 'Croatia' },
  { key: 'cu', value: 'Cuba' },
  { key: 'cw', value: 'Curacao' },
  { key: 'cy', value: 'Cyprus' },
  { key: 'cz', value: 'Czech Republic' },
  { key: 'dk', value: 'Denmark' },
  { key: 'dj', value: 'Djibouti' },
  { key: 'dm', value: 'Dominica' },
  { key: 'do', value: 'Dominican Republic' },
  { key: 'ec', value: 'Ecuador' },
  { key: 'eg', value: 'Egypt' },
  { key: 'sv', value: 'El Salvador' },
  { key: 'gq', value: 'Equatorial Guinea' },
  { key: 'er', value: 'Eritrea' },
  { key: 'ee', value: 'Estonia' },
  { key: 'et', value: 'Ethiopia' },
  { key: 'fk', value: 'Falkland Islands (Malvinas)' },
  { key: 'fo', value: 'Faroe Islands' },
  { key: 'fj', value: 'Fiji' },
  { key: 'fi', value: 'Finland' },
  { key: 'fr', value: 'France' },
  { key: 'gf', value: 'French Guiana' },
  { key: 'pf', value: 'French Polynesia' },
  { key: 'tf', value: 'French Southern Territories' },
  { key: 'ga', value: 'Gabon' },
  { key: 'gm', value: 'Gambia' },
  { key: 'ge', value: 'Georgia' },
  { key: 'de', value: 'Germany' },
  { key: 'gh', value: 'Ghana' },
  { key: 'gi', value: 'Gibraltar' },
  { key: 'gr', value: 'Greece' },
  { key: 'gl', value: 'Greenland' },
  { key: 'gd', value: 'Grenada' },
  { key: 'gp', value: 'Guadeloupe' },
  { key: 'gu', value: 'Guam' },
  { key: 'gt', value: 'Guatemala' },
  { key: 'gg', value: 'Guernsey' },
  { key: 'gn', value: 'Guinea' },
  { key: 'gw', value: 'Guinea-Bissau' },
  { key: 'gy', value: 'Guyana' },
  { key: 'ht', value: 'Haiti' },
  { key: 'hm', value: 'Heard Island and Mcdonald Islands' },
  { key: 'va', value: 'Holy See (Vatican City State)' },
  { key: 'hn', value: 'Honduras' },
  { key: 'hk', value: 'Hong Kong' },
  { key: 'hu', value: 'Hungary' },
  { key: 'is', value: 'Iceland' },
  { key: 'in', value: 'India' },
  { key: 'id', value: 'Indonesia' },
  { key: 'ir', value: 'Iran, Islamic Republic of' },
  { key: 'iq', value: 'Iraq' },
  { key: 'ie', value: 'Ireland' },
  { key: 'im', value: 'Isle of Man' },
  { key: 'il', value: 'Israel' },
  { key: 'it', value: 'Italy' },
  { key: 'jm', value: 'Jamaica' },
  { key: 'jp', value: 'Japan' },
  { key: 'je', value: 'Jersey' },
  { key: 'jo', value: 'Jordan' },
  { key: 'kz', value: 'Kazakhstan' },
  { key: 'ke', value: 'Kenya' },
  { key: 'ki', value: 'Kiribati' },
  { key: 'kp', value: "Korea, Democratic People's Republic of" },
  { key: 'kr', value: 'Korea, Republic of' },
  { key: 'xk', value: 'Kosovo' },
  { key: 'kw', value: 'Kuwait' },
  { key: 'kg', value: 'Kyrgyzstan' },
  { key: 'la', value: "Lao People's Democratic Republic" },
  { key: 'lv', value: 'Latvia' },
  { key: 'lb', value: 'Lebanon' },
  { key: 'ls', value: 'Lesotho' },
  { key: 'lr', value: 'Liberia' },
  { key: 'ly', value: 'Libyan Arab Jamahiriya' },
  { key: 'li', value: 'Liechtenstein' },
  { key: 'lt', value: 'Lithuania' },
  { key: 'lu', value: 'Luxembourg' },
  { key: 'mo', value: 'Macao' },
  { key: 'mk', value: 'Macedonia, the Former Yugoslav Republic of' },
  { key: 'mg', value: 'Madagascar' },
  { key: 'mw', value: 'Malawi' },
  { key: 'my', value: 'Malaysia' },
  { key: 'mv', value: 'Maldives' },
  { key: 'ml', value: 'Mali' },
  { key: 'mt', value: 'Malta' },
  { key: 'mh', value: 'Marshall Islands' },
  { key: 'mq', value: 'Martinique' },
  { key: 'mr', value: 'Mauritania' },
  { key: 'mu', value: 'Mauritius' },
  { key: 'yt', value: 'Mayotte' },
  { key: 'mx', value: 'Mexico' },
  { key: 'fm', value: 'Micronesia, Federated States of' },
  { key: 'md', value: 'Moldova, Republic of' },
  { key: 'mc', value: 'Monaco' },
  { key: 'mn', value: 'Mongolia' },
  { key: 'me', value: 'Montenegro' },
  { key: 'ms', value: 'Montserrat' },
  { key: 'ma', value: 'Morocco' },
  { key: 'mz', value: 'Mozambique' },
  { key: 'mm', value: 'Myanmar' },
  { key: 'na', value: 'Namibia' },
  { key: 'nr', value: 'Nauru' },
  { key: 'np', value: 'Nepal' },
  { key: 'nl', value: 'Netherlands' },
  { key: 'an', value: 'Netherlands Antilles' },
  { key: 'nc', value: 'New Caledonia' },
  { key: 'nz', value: 'New Zealand' },
  { key: 'ni', value: 'Nicaragua' },
  { key: 'ne', value: 'Niger' },
  { key: 'ng', value: 'Nigeria' },
  { key: 'nu', value: 'Niue' },
  { key: 'nf', value: 'Norfolk Island' },
  { key: 'mp', value: 'Northern Mariana Islands' },
  { key: 'no', value: 'Norway' },
  { key: 'om', value: 'Oman' },
  { key: 'pk', value: 'Pakistan' },
  { key: 'pw', value: 'Palau' },
  { key: 'ps', value: 'Palestinian Territory, Occupied' },
  { key: 'pa', value: 'Panama' },
  { key: 'pg', value: 'Papua New Guinea' },
  { key: 'py', value: 'Paraguay' },
  { key: 'pe', value: 'Peru' },
  { key: 'ph', value: 'Philippines' },
  { key: 'pn', value: 'Pitcairn' },
  { key: 'pl', value: 'Poland' },
  { key: 'pt', value: 'Portugal' },
  { key: 'pr', value: 'Puerto Rico' },
  { key: 'qa', value: 'Qatar' },
  { key: 're', value: 'Reunion' },
  { key: 'ro', value: 'Romania' },
  { key: 'ru', value: 'Russian Federation' },
  { key: 'rw', value: 'Rwanda' },
  { key: 'bl', value: 'Saint Barthelemy' },
  { key: 'sh', value: 'Saint Helena' },
  { key: 'kn', value: 'Saint Kitts and Nevis' },
  { key: 'lc', value: 'Saint Lucia' },
  { key: 'mf', value: 'Saint Martin' },
  { key: 'pm', value: 'Saint Pierre and Miquelon' },
  { key: 'vc', value: 'Saint Vincent and the Grenadines' },
  { key: 'ws', value: 'Samoa' },
  { key: 'sm', value: 'San Marino' },
  { key: 'st', value: 'Sao Tome and Principe' },
  { key: 'sa', value: 'Saudi Arabia' },
  { key: 'sn', value: 'Senegal' },
  { key: 'rs', value: 'Serbia' },
  { key: 'cs', value: 'Serbia and Montenegro' },
  { key: 'sc', value: 'Seychelles' },
  { key: 'sl', value: 'Sierra Leone' },
  { key: 'sg', value: 'Singapore' },
  { key: 'sx', value: 'Sint Maarten' },
  { key: 'sk', value: 'Slovakia' },
  { key: 'si', value: 'Slovenia' },
  { key: 'sb', value: 'Solomon Islands' },
  { key: 'so', value: 'Somalia' },
  { key: 'za', value: 'South Africa' },
  { key: 'gs', value: 'South Georgia and the South Sandwich Islands' },
  { key: 'ss', value: 'South Sudan' },
  { key: 'es', value: 'Spain' },
  { key: 'lk', value: 'Sri Lanka' },
  { key: 'sd', value: 'Sudan' },
  { key: 'sr', value: 'Suriname' },
  { key: 'sj', value: 'Svalbard and Jan Mayen' },
  { key: 'sz', value: 'Swaziland' },
  { key: 'se', value: 'Sweden' },
  { key: 'ch', value: 'Switzerland' },
  { key: 'sy', value: 'Syrian Arab Republic' },
  { key: 'tw', value: 'Taiwan, Province of China' },
  { key: 'tj', value: 'Tajikistan' },
  { key: 'tz', value: 'Tanzania, United Republic of' },
  { key: 'th', value: 'Thailand' },
  { key: 'tl', value: 'Timor-Leste' },
  { key: 'tg', value: 'Togo' },
  { key: 'tk', value: 'Tokelau' },
  { key: 'to', value: 'Tonga' },
  { key: 'tt', value: 'Trinidad and Tobago' },
  { key: 'tn', value: 'Tunisia' },
  { key: 'tr', value: 'Turkey' },
  { key: 'tm', value: 'Turkmenistan' },
  { key: 'tc', value: 'Turks and Caicos Islands' },
  { key: 'tv', value: 'Tuvalu' },
  { key: 'ug', value: 'Uganda' },
  { key: 'ua', value: 'Ukraine' },
  { key: 'ae', value: 'United Arab Emirates' },
  { key: 'gb', value: 'United Kingdom' },
  { key: 'us', value: 'United States' },
  { key: 'um', value: 'United States Minor Outlying Islands' },
  { key: 'uy', value: 'Uruguay' },
  { key: 'uz', value: 'Uzbekistan' },
  { key: 'vu', value: 'Vanuatu' },
  { key: 've', value: 'Venezuela' },
  { key: 'vn', value: 'Viet Nam' },
  { key: 'vg', value: 'Virgin Islands, British' },
  { key: 'vi', value: 'Virgin Islands, U.s.' },
  { key: 'wf', value: 'Wallis and Futuna' },
  { key: 'eh', value: 'Western Sahara' },
  { key: 'ye', value: 'Yemen' },
  { key: 'zm', value: 'Zambia' },
  { key: 'zw', value: 'Zimbabwe' },
];
